version: 0.0.0.{build}
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {
      Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME).$($env:APPVEYOR_BUILD_NUMBER)"
    }

    else

    {
      Update-AppveyorBuild -Version "0.0.0.$($env:APPVEYOR_BUILD_NUMBER)-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
    }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
build:
  publish_nuget: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: j5g0Htw7zXZ/iAMHi68yb+9AZIO2bno642h/Djfe62Ux4ZiHIVNg0SpiIgI/BtqG
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
